services:
  go-proxy-bingai:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - HEADLESS=false
      - PASS_TIMEOUT=5
    ports:
      - 7860:7860
      - 8080:8080
      - 9005:9005

  cloudflared:
    build: 
      context: .
      dockerfile: Dockerfile-cloudflared
    container_name: cloudflared
    command: /usr/bin/cloudflared tunnel --no-autoupdate run --token $CF_ZERO_TRUST_TOKEN