services:
  go-proxy-bingai:
    build: 
      context: .
      dockerfile: Dockerfile
      no_cache: true
    environment:
      - HEADLESS=false
      - PASS_TIMEOUT=5
      - CF_ZERO_TRUST_TOKEN=eyJhIjoiYjNlYzhlNmNkZjhjNWUyNTNmY2Q1YWY3MzYxMzlkZmYiLCJ0IjoiOWE2NDdjMDEtZGEwNC00MjE2LTkyZGQtNDlhOWZhY2VmZmViIiwicyI6Ik5UUTNNRGd5TTJNdE9XTXdZUzAwT1dOaUxXSXlNV1F0TTJaallqTXhaREpoWXpJeiJ9
    ports:
      - 8080:8080
      - 45678:45678
      - 9005:9005